### ISSUE TITLE
REST Endpoints

### ISSUE THREAD

**Issue by daluege** [daluege/dograce#5]
• Geben Sie die 20 schnellsten Hunde aus.
• Geben Sie die 5 erfolgreichsten Zwinger aus.
• In welchem Jahr hatte ein Hund das erste Rennen?
• Welche Eltern haben die schnellsten Nachkommen?
• Gibt es Rüden, die besonders viele Nachkommen haben, aber selbst nicht besonders
schnell sind?
• Gibt es Hündinnen, die nur Nachkommen haben, die in den Top 10 sind?
• Welche Hunde sind besonders langsam?
• Welche 10 Hunde haben die höchste durchschnittliche Punktzahl pro Rennen?
• Welche 10 Hunde haben die höchste durchschnittliche Punktzahl pro gelaufenem Meter?

**Comment by niweb** [comment]
Ist das gleiche wie #3
